In [1]:
import numpy

In [3]:
A = numpy.array(list(range(24)))
A = A.reshape((4,6)) + 3
print(A)

[[ 3  4  5  6  7  8]
 [ 9 10 11 12 13 14]
 [15 16 17 18 19 20]
 [21 22 23 24 25 26]]


In [4]:
B = numpy.array(list(range(6)))
B = B.reshape((2,3))
print(B)

[[0 1 2]
 [3 4 5]]


In [8]:
columnCoordinates = numpy.array([1,1])
columnDimensions = A.shape
inputDimensions = B.shape

relativeCoordinates = []
for i, L in enumerate(columnDimensions):
    x = columnCoordinates[i] / (L-1)
    relativeCoordinates.append(x)

relativeCoordiantes = numpy.array(relativeCoordinates)
print(relativeCoordinates)

[0.3333333333333333, 0.2]


In [9]:
C = numpy.copy(B) + 1
D = numpy.multiply(B,C)
print(B)
print(C)
print(D)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[ 0  2  6]
 [12 20 30]]
